# config.yml

backend:
  name: github
  repo: eoinparkinson/tdp-jekyll
  #branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
    - label: "Main Page"
      name: "index-config"
      file: "index.md"
      fields:
        - { label: 'Title', name: 'title', widget: 'hidden', default: 'My awesome site' }
        - { label: 'Hero Title', name: 'hero-title', widget: 'hidden', default: 'Welcome, to my website!' }